/**
 * Agents tool registry.
 *
 * These tools are intentionally API-first:
 * - Each tool maps to one HTTP endpoint in this service.
 * - Tools never expose SQL/table-level execution.
 */

export type ApiToolMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'

export type ApiToolDefinition = {
  name: string
  description: string
  method: ApiToolMethod
  path: string
  tags: string[]
  parameters: {
    type: 'object'
    properties: Record<string, unknown>
    required?: string[]
  }
}

export const apiTools: ApiToolDefinition[] = [
  {
    name: 'bizing.bizes.list',
    description: 'List bizes available to the authenticated user.',
    method: 'GET',
    path: '/api/v1/bizes',
    tags: ['bizes'],
    parameters: {
      type: 'object',
      properties: {
        page: { type: 'number', default: 1 },
        perPage: { type: 'number', default: 20 },
        status: { type: 'string' },
        type: { type: 'string' },
      },
    },
  },
  {
    name: 'bizing.bizes.create',
    description: 'Create a biz and make current user owner.',
    method: 'POST',
    path: '/api/v1/bizes',
    tags: ['bizes'],
    parameters: {
      type: 'object',
      properties: {
        name: { type: 'string' },
        slug: { type: 'string' },
        type: { type: 'string' },
        timezone: { type: 'string' },
        currency: { type: 'string' },
      },
      required: ['name', 'slug'],
    },
  },
  {
    name: 'bizing.locations.publicList',
    description: 'List public active locations for one biz.',
    method: 'GET',
    path: '/api/v1/public/bizes/{bizId}/locations',
    tags: ['locations', 'public'],
    parameters: {
      type: 'object',
      properties: { bizId: { type: 'string' } },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.operations.locationOverview',
    description: 'Return consolidated per-location operational overview for one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/operations/location-overview',
    tags: ['operations', 'locations'],
    parameters: {
      type: 'object',
      properties: { bizId: { type: 'string' } },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.analytics.overview',
    description: 'Return one canonical revenue and booking summary for a biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/analytics/overview',
    tags: ['analytics', 'operations'],
    parameters: {
      type: 'object',
      properties: { bizId: { type: 'string' } },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.calendars.timeline',
    description:
      'Return the calendar story for one window: bindings, rules, holds, and matching bookings.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/calendars/{calendarId}/timeline',
    tags: ['calendars', 'availability', 'timeline'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        calendarId: { type: 'string' },
        startAt: { type: 'string', description: 'ISO datetime' },
        endAt: { type: 'string', description: 'ISO datetime' },
        includeInactive: { type: 'string', enum: ['true', 'false'] },
        includeRules: { type: 'string', enum: ['true', 'false'] },
        includeBookings: { type: 'string', enum: ['true', 'false'] },
        includeHolds: { type: 'string', enum: ['true', 'false'] },
      },
      required: ['bizId', 'calendarId'],
    },
  },
  {
    name: 'bizing.seating.maps.list',
    description: 'List seat maps for one biz, optionally filtered to one resource.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/seat-maps',
    tags: ['seating', 'resources'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        resourceId: { type: 'string' },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.seating.maps.create',
    description: 'Create one seat map attached to a resource or custom subject.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/seat-maps',
    tags: ['seating', 'resources'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        name: { type: 'string' },
        slug: { type: 'string' },
        status: { type: 'string' },
        targetType: { type: 'string' },
        resourceId: { type: 'string' },
        targetSubjectType: { type: 'string' },
        targetSubjectId: { type: 'string' },
        timezone: { type: 'string' },
        layout: { type: 'object' },
        policy: { type: 'object' },
        metadata: { type: 'object' },
      },
      required: ['bizId', 'name', 'slug'],
    },
  },
  {
    name: 'bizing.seating.seats.list',
    description: 'List the concrete seats for one seat map.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/seat-maps/{seatMapId}/seats',
    tags: ['seating'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        seatMapId: { type: 'string' },
      },
      required: ['bizId', 'seatMapId'],
    },
  },
  {
    name: 'bizing.seating.seats.create',
    description: 'Create one selectable seat inside a seat map.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/seat-maps/{seatMapId}/seats',
    tags: ['seating'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        seatMapId: { type: 'string' },
        seatKey: { type: 'string' },
        sectionKey: { type: 'string' },
        rowLabel: { type: 'string' },
        columnLabel: { type: 'string' },
        gridX: { type: 'number' },
        gridY: { type: 'number' },
        sortOrder: { type: 'number' },
        status: { type: 'string' },
        isAccessible: { type: 'boolean' },
        capacity: { type: 'number' },
        attributes: { type: 'object' },
        metadata: { type: 'object' },
      },
      required: ['bizId', 'seatMapId', 'seatKey'],
    },
  },
  {
    name: 'bizing.seating.holds.list',
    description: 'List seat holds for one seat map.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/seat-maps/{seatMapId}/holds',
    tags: ['seating', 'holds'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        seatMapId: { type: 'string' },
      },
      required: ['bizId', 'seatMapId'],
    },
  },
  {
    name: 'bizing.seating.holds.create',
    description: 'Create a temporary checkout hold for one seat.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/seat-maps/{seatMapId}/holds',
    tags: ['seating', 'holds'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        seatMapId: { type: 'string' },
        seatMapSeatId: { type: 'string' },
        bookingOrderId: { type: 'string' },
        bookingOrderLineId: { type: 'string' },
        queueEntryId: { type: 'string' },
        holderUserId: { type: 'string' },
        holderGroupAccountId: { type: 'string' },
        holdType: { type: 'string' },
        holdState: { type: 'string' },
        expiresAt: { type: 'string', description: 'ISO datetime' },
        idempotencyKey: { type: 'string' },
        policySnapshot: { type: 'object' },
        metadata: { type: 'object' },
      },
      required: ['bizId', 'seatMapId', 'seatMapSeatId', 'expiresAt'],
    },
  },
  {
    name: 'bizing.seating.holds.expire',
    description: 'Expire overdue seat holds for one seat map using the canonical release worker entrypoint.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/seat-maps/{seatMapId}/holds/expire',
    tags: ['seating', 'holds'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        seatMapId: { type: 'string' },
        asOf: { type: 'string', description: 'Optional ISO datetime override for deterministic expiry checks.' },
      },
      required: ['bizId', 'seatMapId'],
    },
  },
  {
    name: 'bizing.seating.reservations.create',
    description: 'Create a committed seat reservation and link it to order or fulfillment context.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/seat-maps/{seatMapId}/reservations',
    tags: ['seating', 'reservations'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        seatMapId: { type: 'string' },
        seatMapSeatId: { type: 'string' },
        seatHoldId: { type: 'string' },
        bookingOrderId: { type: 'string' },
        bookingOrderLineId: { type: 'string' },
        fulfillmentUnitId: { type: 'string' },
        queueEntryId: { type: 'string' },
        reservationState: { type: 'string' },
        note: { type: 'string' },
        metadata: { type: 'object' },
      },
      required: ['bizId', 'seatMapId', 'seatMapSeatId'],
    },
  },
  {
    name: 'bizing.instruments.list',
    description: 'List unified instruments such as intake forms, waivers, checklists, and surveys.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/instruments',
    tags: ['instruments', 'compliance'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        status: { type: 'string' },
        instrumentType: { type: 'string' },
        currentOnly: { type: 'boolean' },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.instruments.create',
    description: 'Create one instrument definition in the unified forms/checklists/surveys system.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/instruments',
    tags: ['instruments', 'compliance'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        name: { type: 'string' },
        slug: { type: 'string' },
        instrumentType: { type: 'string' },
        status: { type: 'string' },
        evaluationMode: { type: 'string' },
        schemaSnapshot: { type: 'object' },
        validationPolicy: { type: 'object' },
        completionPolicy: { type: 'object' },
      },
      required: ['bizId', 'name', 'slug', 'instrumentType'],
    },
  },
  {
    name: 'bizing.instrumentRuns.create',
    description: 'Create one runtime instrument run for a target and assignee.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/instrument-runs',
    tags: ['instruments', 'runtime'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        instrumentId: { type: 'string' },
        targetType: { type: 'string' },
        targetRefId: { type: 'string' },
        assigneeSubjectBizId: { type: 'string' },
        assigneeSubjectType: { type: 'string' },
        assigneeSubjectId: { type: 'string' },
        expiresAt: { type: 'string' },
      },
      required: ['bizId', 'instrumentId', 'targetType', 'targetRefId', 'assigneeSubjectBizId', 'assigneeSubjectType', 'assigneeSubjectId'],
    },
  },
  {
    name: 'bizing.messageTemplates.list',
    description: 'List reusable SMS/email/postal/etc templates for one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/message-templates',
    tags: ['communications', 'templates'],
    parameters: {
      type: 'object',
      properties: { bizId: { type: 'string' } },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.marketingCampaigns.list',
    description: 'List marketing campaigns for one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/marketing-campaigns',
    tags: ['communications', 'marketing'],
    parameters: {
      type: 'object',
      properties: { bizId: { type: 'string' } },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.notificationEndpoints.listMine',
    description: 'List notification endpoints owned by the authenticated user.',
    method: 'GET',
    path: '/api/v1/users/me/notification-endpoints',
    tags: ['notifications', 'identity'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        channel: { type: 'string' },
        status: { type: 'string' },
      },
    },
  },
  {
    name: 'bizing.notificationEndpoints.createMine',
    description: 'Create one notification endpoint for the authenticated user.',
    method: 'POST',
    path: '/api/v1/users/me/notification-endpoints',
    tags: ['notifications', 'identity'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        channel: { type: 'string' },
        destination: { type: 'string' },
        status: { type: 'string' },
        isDefault: { type: 'boolean' },
        metadata: { type: 'object' },
      },
      required: ['channel'],
    },
  },
  {
    name: 'bizing.subjectEvents.list',
    description: 'List immutable subject events for one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/subject-events',
    tags: ['events', 'subjects'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        subjectType: { type: 'string' },
        subjectId: { type: 'string' },
        eventType: { type: 'string' },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.subjectEvents.create',
    description: 'Publish one immutable subject event for one biz.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/subject-events',
    tags: ['events', 'subjects'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        subjectType: { type: 'string' },
        subjectId: { type: 'string' },
        eventType: { type: 'string' },
        requestKey: { type: 'string' },
        correlationKey: { type: 'string' },
        payload: { type: 'object' },
      },
      required: ['bizId', 'subjectType', 'subjectId', 'eventType'],
    },
  },
  {
    name: 'bizing.products.create',
    description: 'Create one catalog product.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/products',
    tags: ['products', 'catalog'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        name: { type: 'string' },
        slug: { type: 'string' },
        basePriceMinor: { type: 'number' },
        currency: { type: 'string' },
        type: { type: 'string' },
      },
      required: ['bizId', 'name', 'slug'],
    },
  },
  {
    name: 'bizing.productBundles.create',
    description: 'Create one product bundle shell for a product.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/product-bundles',
    tags: ['products', 'bundles'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        bundleProductId: { type: 'string' },
        pricingMode: { type: 'string' },
        allowPartialSelection: { type: 'boolean' },
      },
      required: ['bizId', 'bundleProductId'],
    },
  },
  {
    name: 'bizing.requirementSets.create',
    description: 'Create one prerequisite/unlock requirement set.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/requirement-sets',
    tags: ['progression', 'requirements'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        name: { type: 'string' },
        slug: { type: 'string' },
        evaluationMode: { type: 'string' },
      },
      required: ['bizId', 'name', 'slug'],
    },
  },
  {
    name: 'bizing.sessionInteractions.create',
    description: 'Record one live-session interaction such as chat, Q&A, poll, or replay.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/session-interactions',
    tags: ['sessions', 'engagement'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        sourceType: { type: 'string' },
        interactionType: { type: 'string' },
        payload: { type: 'object' },
      },
      required: ['bizId', 'sourceType', 'interactionType'],
    },
  },
  {
    name: 'bizing.queueCounters.create',
    description: 'Create one queue counter/window/service point.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/queue-counters',
    tags: ['queues', 'counters'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        queueId: { type: 'string' },
        code: { type: 'string' },
        name: { type: 'string' },
      },
      required: ['bizId', 'queueId', 'code', 'name'],
    },
  },
  {
    name: 'bizing.library.me',
    description: 'Return one unified ownership view for the authenticated customer.',
    method: 'GET',
    path: '/api/v1/me/library',
    tags: ['library', 'customer'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
      },
    },
  },
  {
    name: 'bizing.actions.preview',
    description: 'Preview one canonical business action without committing it.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/actions/preview',
    tags: ['actions', 'preview'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        actionKey: { type: 'string' },
        actionFamily: { type: 'string' },
        targetSubjectType: { type: 'string' },
        targetSubjectId: { type: 'string' },
        sourceInstallationRef: { type: 'string' },
        idempotencyKey: { type: 'string' },
        payload: { type: 'object' },
        metadata: { type: 'object' },
      },
      required: ['bizId', 'actionKey', 'payload'],
    },
  },
  {
    name: 'bizing.actions.execute',
    description: 'Execute one canonical business action through the action backbone.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/actions/execute',
    tags: ['actions', 'execute'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        actionKey: { type: 'string' },
        actionFamily: { type: 'string' },
        targetSubjectType: { type: 'string' },
        targetSubjectId: { type: 'string' },
        sourceInstallationRef: { type: 'string' },
        idempotencyKey: { type: 'string' },
        payload: { type: 'object' },
        metadata: { type: 'object' },
      },
      required: ['bizId', 'actionKey', 'payload'],
    },
  },
  {
    name: 'bizing.actions.publicExecute',
    description: 'Execute one public-safe canonical business action for a customer-facing surface.',
    method: 'POST',
    path: '/api/v1/public/bizes/{bizId}/actions/execute',
    tags: ['actions', 'public'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        actionKey: { type: 'string' },
        actionFamily: { type: 'string' },
        targetSubjectType: { type: 'string' },
        targetSubjectId: { type: 'string' },
        sourceInstallationRef: { type: 'string' },
        idempotencyKey: { type: 'string' },
        payload: { type: 'object' },
        metadata: { type: 'object' },
      },
      required: ['bizId', 'actionKey', 'payload'],
    },
  },
  {
    name: 'bizing.actions.list',
    description: 'List canonical action requests for one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/actions',
    tags: ['actions'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        page: { type: 'number', default: 1 },
        perPage: { type: 'number', default: 20 },
        actionFamily: { type: 'string' },
        actionKey: { type: 'string' },
        status: { type: 'string' },
        intentMode: { type: 'string' },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.events.list',
    description: 'List canonical domain events for one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/events',
    tags: ['events'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        eventFamily: { type: 'string' },
        eventKey: { type: 'string' },
        subjectType: { type: 'string' },
        subjectId: { type: 'string' },
        actionRequestId: { type: 'string' },
        page: { type: 'number', default: 1 },
        perPage: { type: 'number', default: 20 },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.members.list',
    description: 'List members in one biz with their user profile basics.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/members',
    tags: ['members', 'authz'],
    parameters: {
      type: 'object',
      properties: { bizId: { type: 'string' } },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.members.create',
    description: 'Create one biz membership using userId or email.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/members',
    tags: ['members', 'authz'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        userId: { type: 'string' },
        email: { type: 'string' },
        role: { type: 'string' },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.members.update',
    description: 'Update one biz member role.',
    method: 'PATCH',
    path: '/api/v1/bizes/{bizId}/members/{memberId}',
    tags: ['members', 'authz'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        memberId: { type: 'string' },
        role: { type: 'string' },
      },
      required: ['bizId', 'memberId', 'role'],
    },
  },
  {
    name: 'bizing.members.delete',
    description: 'Delete one biz membership.',
    method: 'DELETE',
    path: '/api/v1/bizes/{bizId}/members/{memberId}',
    tags: ['members', 'authz'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        memberId: { type: 'string' },
      },
      required: ['bizId', 'memberId'],
    },
  },
  {
    name: 'bizing.members.offboard',
    description: 'Offboard one biz member with checklist and reason.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/members/{memberId}/offboard',
    tags: ['members', 'authz', 'workflows'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        memberId: { type: 'string' },
        reason: { type: 'string' },
        checklist: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              key: { type: 'string' },
              label: { type: 'string' },
              completed: { type: 'boolean' },
            },
            required: ['key', 'completed'],
          },
        },
        metadata: { type: 'object' },
      },
      required: ['bizId', 'memberId', 'reason', 'checklist'],
    },
  },
  {
    name: 'bizing.invitations.list',
    description: 'List pending and historical biz invitations.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/invitations',
    tags: ['invitations', 'authz'],
    parameters: {
      type: 'object',
      properties: { bizId: { type: 'string' } },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.invitations.create',
    description: 'Create one biz invitation.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/invitations',
    tags: ['invitations', 'authz'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        email: { type: 'string' },
        role: { type: 'string' },
        expiresAt: { type: 'string', description: 'ISO datetime' },
      },
      required: ['bizId', 'email'],
    },
  },
  {
    name: 'bizing.invitations.delete',
    description: 'Delete or revoke one biz invitation.',
    method: 'DELETE',
    path: '/api/v1/bizes/{bizId}/invitations/{invitationId}',
    tags: ['invitations', 'authz'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        invitationId: { type: 'string' },
      },
      required: ['bizId', 'invitationId'],
    },
  },
  {
    name: 'bizing.projections.list',
    description: 'List registered projections for one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/projections',
    tags: ['projections'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        projectionFamily: { type: 'string' },
        status: { type: 'string' },
        page: { type: 'number', default: 1 },
        perPage: { type: 'number', default: 20 },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.projections.documents.list',
    description: 'List rendered projection documents for one projection.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/projections/{projectionId}/documents',
    tags: ['projections'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        projectionId: { type: 'string' },
        subjectType: { type: 'string' },
        subjectId: { type: 'string' },
        status: { type: 'string' },
        page: { type: 'number', default: 1 },
        perPage: { type: 'number', default: 20 },
      },
      required: ['bizId', 'projectionId'],
    },
  },
  {
    name: 'bizing.debug.snapshots.list',
    description: 'List structured debug snapshots for one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/debug-snapshots',
    tags: ['debug', 'projections'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        snapshotFamily: { type: 'string' },
        contextRef: { type: 'string' },
        severity: { type: 'string' },
        page: { type: 'number', default: 1 },
        perPage: { type: 'number', default: 20 },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.reviewQueues.list',
    description: 'List manual review queues for one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/review-queues',
    tags: ['workflows', 'reviews'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        type: { type: 'string' },
        status: { type: 'string' },
        page: { type: 'number', default: 1 },
        perPage: { type: 'number', default: 20 },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.reviewQueueItems.list',
    description: 'List review queue items for one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/review-queue-items',
    tags: ['workflows', 'reviews'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        reviewQueueId: { type: 'string' },
        status: { type: 'string' },
        assignedToUserId: { type: 'string' },
        itemType: { type: 'string' },
        page: { type: 'number', default: 1 },
        perPage: { type: 'number', default: 20 },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.reviewQueueItems.get',
    description: 'Get one review queue item.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/review-queue-items/{reviewQueueItemId}',
    tags: ['workflows', 'reviews'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        reviewQueueItemId: { type: 'string' },
      },
      required: ['bizId', 'reviewQueueItemId'],
    },
  },
  {
    name: 'bizing.workflows.list',
    description: 'List workflow instances for one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/workflows',
    tags: ['workflows'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        status: { type: 'string' },
        workflowKey: { type: 'string' },
        targetType: { type: 'string' },
        actionRequestId: { type: 'string' },
        page: { type: 'number', default: 1 },
        perPage: { type: 'number', default: 20 },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.workflows.get',
    description: 'Get one workflow instance with steps and decisions.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/workflows/{workflowInstanceId}',
    tags: ['workflows'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        workflowInstanceId: { type: 'string' },
      },
      required: ['bizId', 'workflowInstanceId'],
    },
  },
  {
    name: 'bizing.workflows.steps.list',
    description: 'List steps for one workflow instance.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/workflows/{workflowInstanceId}/steps',
    tags: ['workflows'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        workflowInstanceId: { type: 'string' },
      },
      required: ['bizId', 'workflowInstanceId'],
    },
  },
  {
    name: 'bizing.workflows.decisions.list',
    description: 'List decisions for one workflow instance.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/workflows/{workflowInstanceId}/decisions',
    tags: ['workflows'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        workflowInstanceId: { type: 'string' },
      },
      required: ['bizId', 'workflowInstanceId'],
    },
  },
  {
    name: 'bizing.asyncDeliverables.list',
    description: 'List async deliverables for one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/async-deliverables',
    tags: ['workflows', 'async'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        status: { type: 'string' },
        deliverableType: { type: 'string' },
        workflowInstanceId: { type: 'string' },
        page: { type: 'number', default: 1 },
        perPage: { type: 'number', default: 20 },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.asyncDeliverables.get',
    description: 'Get one async deliverable.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/async-deliverables/{asyncDeliverableId}',
    tags: ['workflows', 'async'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        asyncDeliverableId: { type: 'string' },
      },
      required: ['bizId', 'asyncDeliverableId'],
    },
  },
  {
    name: 'bizing.policies.templates.create',
    description: 'Create one reusable policy template.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/policies/templates',
    tags: ['policies', 'governance'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        name: { type: 'string' },
        slug: { type: 'string' },
        domainKey: { type: 'string' },
        policySnapshot: { type: 'object' },
      },
      required: ['bizId', 'name', 'slug', 'domainKey'],
    },
  },
  {
    name: 'bizing.policies.bindings.create',
    description: 'Bind a policy template to a target.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/policies/bindings',
    tags: ['policies', 'governance'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        policyTemplateId: { type: 'string' },
        targetType: { type: 'string' },
      },
      required: ['bizId', 'policyTemplateId', 'targetType'],
    },
  },
  {
    name: 'bizing.api.raw',
    description:
      'Forward one authenticated request to any safe API path under /api/v1 (future-proof fallback when a dedicated tool is not added yet).',
    method: 'POST',
    path: '/api/v1/agents/execute',
    tags: ['core', 'future-proof'],
    parameters: {
      type: 'object',
      properties: {
        tool: { type: 'string', const: 'bizing.api.raw' },
        params: {
          type: 'object',
          properties: {
            method: { type: 'string', enum: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] },
            path: { type: 'string', description: 'Must start with /api/v1/' },
            query: { type: 'object' },
            body: { type: 'object' },
          },
          required: ['method', 'path'],
        },
      },
      required: ['tool', 'params'],
    },
  },
  {
    name: 'bizing.auth.me',
    description: 'Get authenticated user context, memberships, active biz, and effective permissions.',
    method: 'GET',
    path: '/api/v1/auth/me',
    tags: ['auth', 'acl'],
    parameters: {
      type: 'object',
      properties: {},
    },
  },
  {
    name: 'bizing.auth.switchActiveBiz',
    description: 'Switch active biz context for the current session.',
    method: 'PATCH',
    path: '/api/v1/auth/active-biz',
    tags: ['auth'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.auth.apiKeys.list',
    description: 'List machine API keys owned by current user.',
    method: 'GET',
    path: '/api/v1/auth/api-keys',
    tags: ['auth', 'machine'],
    parameters: {
      type: 'object',
      properties: {
        includeRevoked: { type: 'boolean', default: false },
        bizId: { type: 'string' },
        limit: { type: 'number', default: 100 },
      },
    },
  },
  {
    name: 'bizing.auth.apiKeys.create',
    description:
      'Create one machine API key (raw secret returned once). Supports direct-key mode and optional immediate bootstrap bearer token.',
    method: 'POST',
    path: '/api/v1/auth/api-keys',
    tags: ['auth', 'machine'],
    parameters: {
      type: 'object',
      properties: {
        label: { type: 'string' },
        description: { type: 'string' },
        bizId: { type: 'string' },
        scopes: { type: 'array', items: { type: 'string' } },
        expiresAt: { type: 'string', description: 'ISO datetime' },
        allowDirectApiKeyAuth: { type: 'boolean', default: true },
        issueAccessToken: { type: 'object' },
        metadata: { type: 'object' },
      },
      required: ['label'],
    },
  },
  {
    name: 'bizing.auth.apiKeys.rotate',
    description:
      'Rotate one machine API key (create replacement, optionally revoke previous, optionally mint bootstrap bearer token).',
    method: 'POST',
    path: '/api/v1/auth/api-keys/{apiCredentialId}/rotate',
    tags: ['auth', 'machine'],
    parameters: {
      type: 'object',
      properties: {
        apiCredentialId: { type: 'string' },
        label: { type: 'string' },
        description: { type: 'string' },
        scopes: { type: 'array', items: { type: 'string' } },
        expiresAt: { type: 'string', description: 'ISO datetime' },
        allowDirectApiKeyAuth: { type: 'boolean' },
        revokePrevious: { type: 'boolean', default: true },
        revokeReason: { type: 'string' },
        issueAccessToken: { type: 'object' },
      },
      required: ['apiCredentialId'],
    },
  },
  {
    name: 'bizing.auth.apiKeys.revoke',
    description: 'Revoke one API key and all child short-lived tokens.',
    method: 'POST',
    path: '/api/v1/auth/api-keys/{apiCredentialId}/revoke',
    tags: ['auth', 'machine'],
    parameters: {
      type: 'object',
      properties: {
        apiCredentialId: { type: 'string' },
        reason: { type: 'string' },
      },
      required: ['apiCredentialId'],
    },
  },
  {
    name: 'bizing.auth.tokens.list',
    description: 'List short-lived machine bearer tokens owned by current user.',
    method: 'GET',
    path: '/api/v1/auth/tokens',
    tags: ['auth', 'machine'],
    parameters: {
      type: 'object',
      properties: {
        apiCredentialId: { type: 'string' },
        includeRevoked: { type: 'boolean', default: false },
        limit: { type: 'number', default: 100 },
      },
    },
  },
  {
    name: 'bizing.auth.events.list',
    description: 'List auth decision/lifecycle events for observability and incident triage.',
    method: 'GET',
    path: '/api/v1/auth/events',
    tags: ['auth', 'machine', 'observability'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        authSource: { type: 'string' },
        decision: { type: 'string' },
        eventType: { type: 'string' },
        occurredFrom: { type: 'string', description: 'ISO datetime' },
        occurredTo: { type: 'string', description: 'ISO datetime' },
        mineOnly: { type: 'boolean', default: true },
        limit: { type: 'number', default: 200 },
      },
    },
  },
  {
    name: 'bizing.auth.principals.list',
    description: 'List normalized auth principals (sessions/api keys/tokens/system actors).',
    method: 'GET',
    path: '/api/v1/auth/principals',
    tags: ['auth', 'machine', 'observability'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        mineOnly: { type: 'boolean', default: true },
        limit: { type: 'number', default: 200 },
      },
    },
  },
  {
    name: 'bizing.auth.tokens.exchange',
    description:
      'Exchange an API key for a short-lived bearer token. Supports session + apiCredentialId or direct x-api-key auth.',
    method: 'POST',
    path: '/api/v1/auth/tokens/exchange',
    tags: ['auth', 'machine'],
    parameters: {
      type: 'object',
      properties: {
        apiCredentialId: { type: 'string' },
        apiKey: { type: 'string' },
        scopes: { type: 'array', items: { type: 'string' } },
        ttlSeconds: { type: 'number', default: 900 },
        bizId: { type: 'string' },
        reason: { type: 'string' },
      },
    },
  },
  {
    name: 'bizing.auth.tokens.revoke',
    description: 'Revoke one short-lived machine access token.',
    method: 'POST',
    path: '/api/v1/auth/tokens/{tokenId}/revoke',
    tags: ['auth', 'machine'],
    parameters: {
      type: 'object',
      properties: {
        tokenId: { type: 'string' },
        reason: { type: 'string' },
      },
      required: ['tokenId'],
    },
  },
  {
    name: 'bizing.acl.biz.roles.list',
    description: 'List ACL role definitions available to one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/acl/roles',
    tags: ['acl', 'biz'],
    parameters: {
      type: 'object',
      properties: { bizId: { type: 'string' } },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.acl.biz.roles.create',
    description: 'Create biz/location/resource/subject scoped ACL role definition.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/acl/roles',
    tags: ['acl', 'biz'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        roleKey: { type: 'string' },
        name: { type: 'string' },
        scopeType: { type: 'string', enum: ['biz', 'location', 'resource', 'subject'] },
        locationId: { type: 'string' },
        resourceId: { type: 'string' },
        scopeSubjectType: { type: 'string' },
        scopeSubjectId: { type: 'string' },
        description: { type: 'string' },
      },
      required: ['bizId', 'roleKey', 'name'],
    },
  },
  {
    name: 'bizing.acl.biz.rolePermissions.replace',
    description: 'Replace/update one biz role permission set.',
    method: 'PUT',
    path: '/api/v1/bizes/{bizId}/acl/roles/{roleId}/permissions',
    tags: ['acl', 'biz'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        roleId: { type: 'string' },
        permissions: { type: 'array', items: { type: 'object' } },
      },
      required: ['bizId', 'roleId', 'permissions'],
    },
  },
  {
    name: 'bizing.acl.biz.assignments.create',
    description: 'Assign ACL role to a user at biz/location/resource/subject scope.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/acl/assignments',
    tags: ['acl', 'biz'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        userId: { type: 'string' },
        roleDefinitionId: { type: 'string' },
        scopeType: { type: 'string', enum: ['biz', 'location', 'resource', 'subject'] },
        locationId: { type: 'string' },
        resourceId: { type: 'string' },
        scopeSubjectType: { type: 'string' },
        scopeSubjectId: { type: 'string' },
      },
      required: ['bizId', 'userId', 'roleDefinitionId'],
    },
  },
  {
    name: 'bizing.acl.biz.mappings.replace',
    description: 'Replace membership role -> ACL role mappings for one biz.',
    method: 'PUT',
    path: '/api/v1/bizes/{bizId}/acl/membership-mappings',
    tags: ['acl', 'biz'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        mappings: { type: 'array', items: { type: 'object' } },
      },
      required: ['bizId', 'mappings'],
    },
  },
  {
    name: 'bizing.acl.platform.roles.list',
    description: 'List platform-level ACL role templates.',
    method: 'GET',
    path: '/api/v1/platform/acl/roles',
    tags: ['acl', 'platform'],
    parameters: {
      type: 'object',
      properties: {},
    },
  },
  {
    name: 'bizing.acl.platform.permissions.list',
    description: 'List global ACL permission definitions.',
    method: 'GET',
    path: '/api/v1/platform/acl/permissions',
    tags: ['acl', 'platform'],
    parameters: {
      type: 'object',
      properties: {},
    },
  },
  {
    name: 'bizing.acl.platform.assignments.create',
    description: 'Assign a platform ACL role to a user.',
    method: 'POST',
    path: '/api/v1/platform/acl/assignments',
    tags: ['acl', 'platform'],
    parameters: {
      type: 'object',
      properties: {
        userId: { type: 'string' },
        roleDefinitionId: { type: 'string' },
      },
      required: ['userId', 'roleDefinitionId'],
    },
  },
  {
    name: 'bizing.locations.list',
    description: 'List locations for one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/locations',
    tags: ['locations'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        page: { type: 'number', default: 1 },
        perPage: { type: 'number', default: 20 },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.locations.create',
    description: 'Create location in one biz.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/locations',
    tags: ['locations'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        name: { type: 'string' },
        slug: { type: 'string' },
        type: { type: 'string' },
        timezone: { type: 'string' },
      },
      required: ['bizId', 'name', 'slug'],
    },
  },
  {
    name: 'bizing.resources.list',
    description: 'List resources for one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/resources',
    tags: ['resources'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        type: { type: 'string' },
        locationId: { type: 'string' },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.resources.create',
    description: 'Create resource in one biz.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/resources',
    tags: ['resources'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        locationId: { type: 'string' },
        type: { type: 'string' },
        name: { type: 'string' },
        slug: { type: 'string' },
      },
      required: ['bizId', 'locationId', 'type', 'name', 'slug'],
    },
  },
  {
    name: 'bizing.serviceGroups.list',
    description: 'List service groups in one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/service-groups',
    tags: ['services'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        status: { type: 'string' },
        search: { type: 'string' },
        page: { type: 'number', default: 1 },
        perPage: { type: 'number', default: 20 },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.serviceGroups.create',
    description: 'Create one service group in one biz.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/service-groups',
    tags: ['services'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        name: { type: 'string' },
        slug: { type: 'string' },
        description: { type: 'string' },
        status: { type: 'string' },
      },
      required: ['bizId', 'name', 'slug'],
    },
  },
  {
    name: 'bizing.services.list',
    description: 'List service templates in one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/services',
    tags: ['services'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        serviceGroupId: { type: 'string' },
        type: { type: 'string' },
        visibility: { type: 'string' },
        status: { type: 'string' },
        search: { type: 'string' },
        page: { type: 'number', default: 1 },
        perPage: { type: 'number', default: 20 },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.services.create',
    description: 'Create one service template in one biz.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/services',
    tags: ['services'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        serviceGroupId: { type: 'string' },
        name: { type: 'string' },
        slug: { type: 'string' },
        type: { type: 'string' },
        visibility: { type: 'string' },
        requiresApproval: { type: 'boolean' },
        allowWaitlist: { type: 'boolean' },
      },
      required: ['bizId', 'serviceGroupId', 'name', 'slug'],
    },
  },
  {
    name: 'bizing.serviceProducts.list',
    description: 'List service products in one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/service-products',
    tags: ['service-products'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        status: { type: 'string' },
        kind: { type: 'string' },
        durationMode: { type: 'string' },
        isPublished: { type: 'boolean' },
        search: { type: 'string' },
        page: { type: 'number', default: 1 },
        perPage: { type: 'number', default: 20 },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.serviceProducts.create',
    description: 'Create one service product in one biz.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/service-products',
    tags: ['service-products'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        name: { type: 'string' },
        slug: { type: 'string' },
        kind: { type: 'string' },
        durationMode: { type: 'string' },
        defaultDurationMinutes: { type: 'number' },
        basePriceAmountMinorUnits: { type: 'number' },
        currency: { type: 'string' },
        isPublished: { type: 'boolean' },
        status: { type: 'string' },
      },
      required: ['bizId', 'name', 'slug'],
    },
  },
  {
    name: 'bizing.serviceProducts.bindings.list',
    description: 'List service bindings for one service product.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/service-products/{serviceProductId}/services',
    tags: ['service-products', 'services'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        serviceProductId: { type: 'string' },
        requirementMode: { type: 'string' },
      },
      required: ['bizId', 'serviceProductId'],
    },
  },
  {
    name: 'bizing.serviceProducts.bindings.create',
    description: 'Add a service/service-group binding to one service product.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/service-products/{serviceProductId}/services',
    tags: ['service-products', 'services'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        serviceProductId: { type: 'string' },
        serviceId: { type: 'string' },
        serviceGroupId: { type: 'string' },
        requirementMode: { type: 'string' },
        minQuantity: { type: 'number' },
        maxQuantity: { type: 'number' },
      },
      required: ['bizId', 'serviceProductId'],
    },
  },
  {
    name: 'bizing.calendars.list',
    description: 'List calendars in one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/calendars',
    tags: ['calendars'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        status: { type: 'string' },
        defaultMode: { type: 'string' },
        search: { type: 'string' },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.calendars.create',
    description: 'Create a calendar in one biz.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/calendars',
    tags: ['calendars'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        name: { type: 'string' },
        timezone: { type: 'string' },
        slotDurationMin: { type: 'number' },
        slotIntervalMin: { type: 'number' },
        minAdvanceBookingHours: { type: 'number' },
        maxAdvanceBookingDays: { type: 'number' },
        defaultMode: { type: 'string' },
      },
      required: ['bizId', 'name'],
    },
  },
  {
    name: 'bizing.calendarBindings.list',
    description: 'List calendar bindings (owner -> calendar mappings) in one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/calendar-bindings',
    tags: ['calendars'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        ownerType: { type: 'string' },
        ownerRefKey: { type: 'string' },
        calendarId: { type: 'string' },
        isPrimary: { type: 'boolean' },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.calendarBindings.create',
    description: 'Create one owner -> calendar binding in one biz.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/calendar-bindings',
    tags: ['calendars'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        calendarId: { type: 'string' },
        ownerType: { type: 'string' },
        resourceId: { type: 'string' },
        serviceId: { type: 'string' },
        serviceProductId: { type: 'string' },
        offerId: { type: 'string' },
        offerVersionId: { type: 'string' },
        locationId: { type: 'string' },
        ownerUserId: { type: 'string' },
        ownerRefType: { type: 'string' },
        ownerRefId: { type: 'string' },
        isPrimary: { type: 'boolean' },
      },
      required: ['bizId', 'calendarId', 'ownerType'],
    },
  },
  {
    name: 'bizing.availabilityRules.list',
    description: 'List availability rules for one calendar.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/calendars/{calendarId}/availability-rules',
    tags: ['calendars', 'availability'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        calendarId: { type: 'string' },
        mode: { type: 'string' },
        action: { type: 'string' },
        isActive: { type: 'boolean' },
      },
      required: ['bizId', 'calendarId'],
    },
  },
  {
    name: 'bizing.availabilityRules.create',
    description: 'Create one availability rule for one calendar.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/calendars/{calendarId}/availability-rules',
    tags: ['calendars', 'availability'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        calendarId: { type: 'string' },
        name: { type: 'string' },
        mode: { type: 'string' },
        frequency: { type: 'string' },
        startDate: { type: 'string' },
        endDate: { type: 'string' },
        startTime: { type: 'string' },
        endTime: { type: 'string' },
        startAt: { type: 'string' },
        endAt: { type: 'string' },
        action: { type: 'string' },
        priority: { type: 'number' },
      },
      required: ['bizId', 'calendarId', 'name', 'mode', 'action'],
    },
  },
  {
    name: 'bizing.integrations.channelAccounts.list',
    description: 'List external integration channel accounts for one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/channel-accounts',
    tags: ['integrations', 'channels'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        provider: { type: 'string' },
        status: { type: 'string' },
        page: { type: 'number', default: 1 },
        perPage: { type: 'number', default: 20 },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.integrations.channelAccounts.create',
    description: 'Create one external integration channel account in a biz.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/channel-accounts',
    tags: ['integrations', 'channels'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        provider: { type: 'string' },
        name: { type: 'string' },
        status: { type: 'string' },
        providerAccountRef: { type: 'string' },
        scopes: { type: 'array', items: { type: 'string' } },
        authConfig: { type: 'object' },
        metadata: { type: 'object' },
      },
      required: ['bizId', 'provider', 'name'],
    },
  },
  {
    name: 'bizing.integrations.channelSyncStates.list',
    description: 'List channel sync states (cursor/sync health checkpoints).',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/channel-sync-states',
    tags: ['integrations', 'channels', 'sync'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        channelAccountId: { type: 'string' },
        objectType: { type: 'string' },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.integrations.channelSyncStates.upsert',
    description: 'Create or update channel sync checkpoint state for one account/object type.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/channel-sync-states',
    tags: ['integrations', 'channels', 'sync'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        channelAccountId: { type: 'string' },
        objectType: { type: 'string' },
        direction: { type: 'string' },
        inboundCursor: { type: 'string' },
        outboundCursor: { type: 'string' },
        lastFailure: { type: 'string' },
        lastAttemptAt: { type: 'string' },
        lastSuccessAt: { type: 'string' },
        metadata: { type: 'object' },
      },
      required: ['bizId', 'channelAccountId', 'objectType', 'direction'],
    },
  },
  {
    name: 'bizing.integrations.channelEntityLinks.list',
    description: 'List local-to-external ID mappings for channels.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/channel-entity-links',
    tags: ['integrations', 'channels', 'external-id'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        channelAccountId: { type: 'string' },
        objectType: { type: 'string' },
        isActive: { type: 'boolean' },
        page: { type: 'number', default: 1 },
        perPage: { type: 'number', default: 20 },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.integrations.channelEntityLinks.create',
    description: 'Create one external ID mapping row for channel sync tracking.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/channel-entity-links',
    tags: ['integrations', 'channels', 'external-id'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        channelAccountId: { type: 'string' },
        objectType: { type: 'string' },
        offerVersionId: { type: 'string' },
        bookingOrderId: { type: 'string' },
        resourceId: { type: 'string' },
        customerUserId: { type: 'string' },
        localReferenceKey: { type: 'string' },
        externalObjectId: { type: 'string' },
        externalParentId: { type: 'string' },
        syncHash: { type: 'string' },
        isActive: { type: 'boolean' },
        metadata: { type: 'object' },
      },
      required: ['bizId', 'channelAccountId', 'objectType', 'externalObjectId'],
    },
  },
  {
    name: 'bizing.offers.list',
    description: 'List offers for one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/offers',
    tags: ['offers'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        status: { type: 'string' },
        executionMode: { type: 'string' },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.offers.create',
    description: 'Create offer in one biz.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/offers',
    tags: ['offers'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        name: { type: 'string' },
        slug: { type: 'string' },
        executionMode: { type: 'string' },
      },
      required: ['bizId', 'name', 'slug'],
    },
  },
  {
    name: 'bizing.offers.createVersion',
    description: 'Create a new offer version.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/offers/{offerId}/versions',
    tags: ['offers', 'versions'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        offerId: { type: 'string' },
        version: { type: 'number' },
        durationMode: { type: 'string' },
        basePriceMinor: { type: 'number' },
      },
      required: ['bizId', 'offerId', 'version'],
    },
  },
  {
    name: 'bizing.public.offers.list',
    description: 'List publicly published offers for one biz (customer discovery surface).',
    method: 'GET',
    path: '/api/v1/public/bizes/{bizId}/offers',
    tags: ['offers', 'public'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        search: { type: 'string' },
        limit: { type: 'number', default: 50 },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.bookingOrders.list',
    description: 'List booking orders for one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/booking-orders',
    tags: ['booking-orders'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        status: { type: 'string' },
        page: { type: 'number', default: 1 },
        perPage: { type: 'number', default: 20 },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.bookingOrders.create',
    description: 'Create booking order in one biz.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/booking-orders',
    tags: ['booking-orders'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        offerId: { type: 'string' },
        offerVersionId: { type: 'string' },
        totalMinor: { type: 'number' },
        currency: { type: 'string' },
      },
      required: ['bizId', 'offerId', 'offerVersionId'],
    },
  },
  {
    name: 'bizing.public.bookingOrders.listMine',
    description: 'List authenticated customer bookings for one biz on the public booking surface.',
    method: 'GET',
    path: '/api/v1/public/bizes/{bizId}/booking-orders',
    tags: ['booking-orders', 'public'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        status: { type: 'string' },
        page: { type: 'number', default: 1 },
        perPage: { type: 'number', default: 20 },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.public.bookingOrders.create',
    description: 'Create customer booking on the public booking surface.',
    method: 'POST',
    path: '/api/v1/public/bizes/{bizId}/booking-orders',
    tags: ['booking-orders', 'public'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        offerId: { type: 'string' },
        offerVersionId: { type: 'string' },
        totalMinor: { type: 'number' },
        currency: { type: 'string' },
        requestedStartAt: { type: 'string', description: 'ISO datetime' },
        requestedEndAt: { type: 'string', description: 'ISO datetime' },
      },
      required: ['bizId', 'offerId', 'offerVersionId'],
    },
  },
  {
    name: 'bizing.queues.list',
    description: 'List queue/waitlist definitions for one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/queues',
    tags: ['queues', 'waitlist'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        locationId: { type: 'string' },
        status: { type: 'string', enum: ['active', 'paused', 'closed', 'archived'] },
        strategy: { type: 'string', enum: ['fifo', 'priority', 'weighted', 'fair_share'] },
        selfJoinOnly: { type: 'boolean' },
        search: { type: 'string' },
        page: { type: 'number', default: 1 },
        perPage: { type: 'number', default: 20 },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.queues.create',
    description: 'Create one queue/waitlist definition in a biz.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/queues',
    tags: ['queues', 'waitlist'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        locationId: { type: 'string' },
        name: { type: 'string' },
        slug: { type: 'string' },
        description: { type: 'string' },
        strategy: { type: 'string', enum: ['fifo', 'priority', 'weighted', 'fair_share'] },
        status: { type: 'string', enum: ['active', 'paused', 'closed', 'archived'] },
        isSelfJoinEnabled: { type: 'boolean', default: true },
        policy: { type: 'object' },
        metadata: { type: 'object' },
      },
      required: ['bizId', 'name', 'slug'],
    },
  },
  {
    name: 'bizing.queueEntries.list',
    description: 'List queue entries for one queue in one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/queues/{queueId}/entries',
    tags: ['queues', 'waitlist', 'queue-entries'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        queueId: { type: 'string' },
        status: { type: 'string' },
        customerUserId: { type: 'string' },
        page: { type: 'number', default: 1 },
        perPage: { type: 'number', default: 20 },
      },
      required: ['bizId', 'queueId'],
    },
  },
  {
    name: 'bizing.queueEntries.create',
    description: 'Create one queue entry (internal operator/admin flow).',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/queues/{queueId}/entries',
    tags: ['queues', 'waitlist', 'queue-entries'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        queueId: { type: 'string' },
        customerUserId: { type: 'string' },
        customerGroupAccountId: { type: 'string' },
        requestedOfferVersionId: { type: 'string' },
        priorityScore: { type: 'number', default: 0 },
        displayCode: { type: 'string' },
        metadata: { type: 'object' },
      },
      required: ['bizId', 'queueId'],
    },
  },
  {
    name: 'bizing.queueEntries.update',
    description: 'Update one queue entry status/priority.',
    method: 'PATCH',
    path: '/api/v1/bizes/{bizId}/queues/{queueId}/entries/{queueEntryId}',
    tags: ['queues', 'waitlist', 'queue-entries'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        queueId: { type: 'string' },
        queueEntryId: { type: 'string' },
        status: { type: 'string' },
        priorityScore: { type: 'number' },
        estimatedWaitMin: { type: 'number' },
        metadata: { type: 'object' },
      },
      required: ['bizId', 'queueId', 'queueEntryId'],
    },
  },
  {
    name: 'bizing.public.waitlist.queues.list',
    description: 'List public self-join queues for one biz (customer discovery).',
    method: 'GET',
    path: '/api/v1/public/bizes/{bizId}/queues',
    tags: ['queues', 'waitlist', 'public'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        locationId: { type: 'string' },
        search: { type: 'string' },
        limit: { type: 'number', default: 50 },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.public.waitlist.join',
    description: 'Join queue/waitlist as authenticated customer.',
    method: 'POST',
    path: '/api/v1/public/bizes/{bizId}/queues/{queueId}/entries',
    tags: ['queues', 'waitlist', 'public'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        queueId: { type: 'string' },
        requestedOfferVersionId: { type: 'string' },
        bookingOrderId: { type: 'string' },
        priorityScore: { type: 'number', default: 0 },
        displayCode: { type: 'string' },
        metadata: { type: 'object' },
      },
      required: ['bizId', 'queueId'],
    },
  },
  {
    name: 'bizing.public.waitlist.mine',
    description: 'List my queue/waitlist entries for one queue.',
    method: 'GET',
    path: '/api/v1/public/bizes/{bizId}/queues/{queueId}/entries',
    tags: ['queues', 'waitlist', 'public'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        queueId: { type: 'string' },
        status: { type: 'string' },
        page: { type: 'number', default: 1 },
        perPage: { type: 'number', default: 20 },
      },
      required: ['bizId', 'queueId'],
    },
  },
  {
    name: 'bizing.pricing.demandPolicies.list',
    description: 'List demand-pricing policies for one biz.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/demand-pricing/policies',
    tags: ['pricing', 'demand-pricing'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        status: { type: 'string' },
        targetType: { type: 'string' },
        isEnabled: { type: 'boolean' },
        search: { type: 'string' },
        page: { type: 'number', default: 1 },
        perPage: { type: 'number', default: 20 },
        sortBy: { type: 'string', enum: ['id', 'priority'] },
        sortOrder: { type: 'string', enum: ['asc', 'desc'] },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.pricing.demandPolicies.create',
    description: 'Create one demand-pricing policy row for a biz.',
    method: 'POST',
    path: '/api/v1/bizes/{bizId}/demand-pricing/policies',
    tags: ['pricing', 'demand-pricing'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        name: { type: 'string' },
        slug: { type: 'string' },
        description: { type: 'string' },
        status: { type: 'string' },
        targetType: { type: 'string' },
        resourceId: { type: 'string' },
        serviceId: { type: 'string' },
        serviceProductId: { type: 'string' },
        offerId: { type: 'string' },
        offerVersionId: { type: 'string' },
        locationId: { type: 'string' },
        scoringMode: { type: 'string' },
        scoreFloor: { type: 'number' },
        scoreCeiling: { type: 'number' },
        defaultAdjustmentType: { type: 'string' },
        defaultApplyAs: { type: 'string' },
        defaultAdjustmentValue: { type: 'number' },
        minAdjustmentMinor: { type: 'number' },
        maxAdjustmentMinor: { type: 'number' },
        minFinalUnitPriceMinor: { type: 'number' },
        maxFinalUnitPriceMinor: { type: 'number' },
        cooldownMin: { type: 'number' },
        effectiveStartAt: { type: 'string' },
        effectiveEndAt: { type: 'string' },
        priority: { type: 'number' },
        isEnabled: { type: 'boolean' },
        policy: { type: 'object' },
        metadata: { type: 'object' },
      },
      required: ['bizId', 'name'],
    },
  },
  {
    name: 'bizing.compliance.controls.get',
    description:
      'Read compliance controls snapshot for one biz (privacy scope, credential governance, audit chain counters).',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/compliance/controls',
    tags: ['compliance', 'privacy', 'credential', 'audit'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        includeCredentialSamples: { type: 'boolean', default: false },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.public.payments.advancedCheckout',
    description:
      'Execute advanced checkout for one customer booking (split tender, tip, and line allocations).',
    method: 'POST',
    path: '/api/v1/public/bizes/{bizId}/booking-orders/{bookingOrderId}/payments/advanced',
    tags: ['payments', 'public', 'split-tender'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        bookingOrderId: { type: 'string' },
        currency: { type: 'string' },
        tipMinor: { type: 'number', default: 0 },
        tenders: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              methodType: { type: 'string' },
              allocatedMinor: { type: 'number' },
              provider: { type: 'string' },
              providerMethodRef: { type: 'string' },
              label: { type: 'string' },
              metadata: { type: 'object' },
            },
          },
        },
        metadata: { type: 'object' },
      },
      required: ['bizId', 'bookingOrderId', 'tenders'],
    },
  },
  {
    name: 'bizing.payments.intents.list',
    description: 'List payment intents in one biz with optional booking/status filters.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/payment-intents',
    tags: ['payments', 'intents'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        bookingOrderId: { type: 'string' },
        customerUserId: { type: 'string' },
        status: { type: 'string' },
        page: { type: 'number', default: 1 },
        perPage: { type: 'number', default: 20 },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.payments.intents.get',
    description: 'Get one payment intent with split-tender rows and immutable transaction trail.',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/payment-intents/{paymentIntentId}',
    tags: ['payments', 'intents'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        paymentIntentId: { type: 'string' },
      },
      required: ['bizId', 'paymentIntentId'],
    },
  },
  {
    name: 'bizing.bookingOrders.updateStatus',
    description: 'Update booking order status.',
    method: 'PATCH',
    path: '/api/v1/bizes/{bizId}/booking-orders/{bookingOrderId}/status',
    tags: ['booking-orders'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        bookingOrderId: { type: 'string' },
        status: { type: 'string' },
      },
      required: ['bizId', 'bookingOrderId', 'status'],
    },
  },
  {
    name: 'bizing.dispatch.state.get',
    description:
      'Read one biz dispatch/transport operational snapshot (tasks, trips, routes, upcoming window).',
    method: 'GET',
    path: '/api/v1/bizes/{bizId}/dispatch/state',
    tags: ['dispatch', 'transport', 'routes'],
    parameters: {
      type: 'object',
      properties: {
        bizId: { type: 'string' },
        lookaheadHours: { type: 'number', default: 72 },
        perEntityLimit: { type: 'number', default: 20 },
      },
      required: ['bizId'],
    },
  },
  {
    name: 'bizing.sagas.specs.list',
    description: 'List available saga definitions (file-synced test lifecycles).',
    method: 'GET',
    path: '/api/v1/sagas/specs',
    tags: ['sagas', 'specs'],
    parameters: {
      type: 'object',
      properties: {
        status: { type: 'string' },
        sync: { type: 'boolean' },
        limit: { type: 'number', default: 200 },
      },
    },
  },
  {
    name: 'bizing.sagas.specs.generate',
    description: 'Generate saga JSON specs from use-case + persona markdown sources.',
    method: 'POST',
    path: '/api/v1/sagas/specs/generate',
    tags: ['sagas', 'specs', 'generator'],
    parameters: {
      type: 'object',
      properties: {
        useCaseRefs: { type: 'array', items: { type: 'string' } },
        personaRefs: { type: 'array', items: { type: 'string' } },
        limitUseCases: { type: 'number' },
        maxPersonasPerUseCase: { type: 'number' },
        overwrite: { type: 'boolean', default: true },
        syncDefinitions: { type: 'boolean', default: true },
      },
    },
  },
  {
    name: 'bizing.sagas.library.syncDocs',
    description:
      'Import and normalize use-cases/personas from markdown docs into DB loop tables, then link saga definitions.',
    method: 'POST',
    path: '/api/v1/sagas/library/sync-docs',
    tags: ['sagas', 'library', 'sync'],
    parameters: {
      type: 'object',
      properties: {
        useCaseFile: { type: 'string' },
        personaFile: { type: 'string' },
        linkSagaDefinitions: { type: 'boolean', default: true },
      },
    },
  },
  {
    name: 'bizing.sagas.library.overview',
    description: 'Get aggregate loop counts (UCs/personas/sagas/runs/coverage).',
    method: 'GET',
    path: '/api/v1/sagas/library/overview',
    tags: ['sagas', 'library'],
    parameters: {
      type: 'object',
      properties: {},
    },
  },
  {
    name: 'bizing.sagas.useCases.list',
    description: 'List normalized UC entities used by saga loop.',
    method: 'GET',
    path: '/api/v1/sagas/use-cases',
    tags: ['sagas', 'library', 'use-cases'],
    parameters: {
      type: 'object',
      properties: {
        status: { type: 'string' },
        limit: { type: 'number', default: 500 },
      },
    },
  },
  {
    name: 'bizing.sagas.useCases.create',
    description: 'Create one top-level use-case definition.',
    method: 'POST',
    path: '/api/v1/sagas/use-cases',
    tags: ['sagas', 'library', 'use-cases'],
    parameters: {
      type: 'object',
      properties: {
        ucKey: { type: 'string' },
        title: { type: 'string' },
        status: { type: 'string' },
        summary: { type: 'string' },
        sourceFilePath: { type: 'string' },
        sourceRef: { type: 'string' },
      },
      required: ['ucKey', 'title'],
    },
  },
  {
    name: 'bizing.sagas.useCases.get',
    description: 'Get one use-case with full version history.',
    method: 'GET',
    path: '/api/v1/sagas/use-cases/{ucKey}',
    tags: ['sagas', 'library', 'use-cases'],
    parameters: {
      type: 'object',
      properties: {
        ucKey: { type: 'string' },
      },
      required: ['ucKey'],
    },
  },
  {
    name: 'bizing.sagas.useCases.update',
    description: 'Update top-level use-case metadata.',
    method: 'PATCH',
    path: '/api/v1/sagas/use-cases/{ucKey}',
    tags: ['sagas', 'library', 'use-cases'],
    parameters: {
      type: 'object',
      properties: {
        ucKey: { type: 'string' },
        title: { type: 'string' },
        status: { type: 'string' },
        summary: { type: 'string' },
        sourceFilePath: { type: 'string' },
        sourceRef: { type: 'string' },
      },
      required: ['ucKey'],
    },
  },
  {
    name: 'bizing.sagas.useCases.versions.create',
    description: 'Create one immutable use-case version snapshot.',
    method: 'POST',
    path: '/api/v1/sagas/use-cases/{ucKey}/versions',
    tags: ['sagas', 'library', 'use-cases'],
    parameters: {
      type: 'object',
      properties: {
        ucKey: { type: 'string' },
        title: { type: 'string' },
        summary: { type: 'string' },
        bodyMarkdown: { type: 'string' },
        extractedNeeds: { type: 'array', items: { type: 'string' } },
        extractedScenario: { type: 'string' },
        isCurrent: { type: 'boolean' },
      },
      required: ['ucKey', 'bodyMarkdown'],
    },
  },
  {
    name: 'bizing.sagas.useCases.delete',
    description: 'Delete one use-case definition and its versions.',
    method: 'DELETE',
    path: '/api/v1/sagas/use-cases/{ucKey}',
    tags: ['sagas', 'library', 'use-cases'],
    parameters: {
      type: 'object',
      properties: {
        ucKey: { type: 'string' },
      },
      required: ['ucKey'],
    },
  },
  {
    name: 'bizing.sagas.personas.list',
    description: 'List normalized persona entities used by saga loop.',
    method: 'GET',
    path: '/api/v1/sagas/personas',
    tags: ['sagas', 'library', 'personas'],
    parameters: {
      type: 'object',
      properties: {
        status: { type: 'string' },
        limit: { type: 'number', default: 500 },
      },
    },
  },
  {
    name: 'bizing.sagas.personas.create',
    description: 'Create one top-level persona definition.',
    method: 'POST',
    path: '/api/v1/sagas/personas',
    tags: ['sagas', 'library', 'personas'],
    parameters: {
      type: 'object',
      properties: {
        personaKey: { type: 'string' },
        name: { type: 'string' },
        status: { type: 'string' },
        profileSummary: { type: 'string' },
        sourceFilePath: { type: 'string' },
        sourceRef: { type: 'string' },
      },
      required: ['personaKey', 'name'],
    },
  },
  {
    name: 'bizing.sagas.personas.get',
    description: 'Get one persona with full version history.',
    method: 'GET',
    path: '/api/v1/sagas/personas/{personaKey}',
    tags: ['sagas', 'library', 'personas'],
    parameters: {
      type: 'object',
      properties: {
        personaKey: { type: 'string' },
      },
      required: ['personaKey'],
    },
  },
  {
    name: 'bizing.sagas.personas.update',
    description: 'Update top-level persona metadata.',
    method: 'PATCH',
    path: '/api/v1/sagas/personas/{personaKey}',
    tags: ['sagas', 'library', 'personas'],
    parameters: {
      type: 'object',
      properties: {
        personaKey: { type: 'string' },
        name: { type: 'string' },
        status: { type: 'string' },
        profileSummary: { type: 'string' },
        sourceFilePath: { type: 'string' },
        sourceRef: { type: 'string' },
      },
      required: ['personaKey'],
    },
  },
  {
    name: 'bizing.sagas.personas.versions.create',
    description: 'Create one immutable persona version snapshot.',
    method: 'POST',
    path: '/api/v1/sagas/personas/{personaKey}/versions',
    tags: ['sagas', 'library', 'personas'],
    parameters: {
      type: 'object',
      properties: {
        personaKey: { type: 'string' },
        name: { type: 'string' },
        profile: { type: 'string' },
        goals: { type: 'string' },
        painPoints: { type: 'string' },
        testScenarios: { type: 'array', items: { type: 'string' } },
        bodyMarkdown: { type: 'string' },
        isCurrent: { type: 'boolean' },
      },
      required: ['personaKey', 'bodyMarkdown'],
    },
  },
  {
    name: 'bizing.sagas.personas.delete',
    description: 'Delete one persona definition and its versions.',
    method: 'DELETE',
    path: '/api/v1/sagas/personas/{personaKey}',
    tags: ['sagas', 'library', 'personas'],
    parameters: {
      type: 'object',
      properties: {
        personaKey: { type: 'string' },
      },
      required: ['personaKey'],
    },
  },
  {
    name: 'bizing.sagas.library.related',
    description:
      'Get one UC/persona node and all linked saga definitions (design-to-execution mapping).',
    method: 'GET',
    path: '/api/v1/sagas/library/related',
    tags: ['sagas', 'library', 'relations'],
    parameters: {
      type: 'object',
      properties: {
        kind: { type: 'string', enum: ['use_case', 'persona'] },
        key: { type: 'string' },
      },
      required: ['kind', 'key'],
    },
  },
  {
    name: 'bizing.sagas.definitions.links.get',
    description: 'Get linked UC/persona versions for one saga definition.',
    method: 'GET',
    path: '/api/v1/sagas/definitions/{sagaKey}/links',
    tags: ['sagas', 'links'],
    parameters: {
      type: 'object',
      properties: {
        sagaKey: { type: 'string' },
      },
      required: ['sagaKey'],
    },
  },
  {
    name: 'bizing.sagas.runAssessments.reports.list',
    description: 'List run-assessment coverage reports generated from saga executions.',
    method: 'GET',
    path: '/api/v1/sagas/run-assessments/reports',
    tags: ['sagas', 'run-assessment'],
    parameters: {
      type: 'object',
      properties: {
        sagaRunId: { type: 'string' },
        sagaDefinitionId: { type: 'string' },
        limit: { type: 'number', default: 100 },
      },
    },
  },
  {
    name: 'bizing.sagas.runAssessments.reports.get',
    description: 'Get one run-assessment coverage report with normalized coverage items and tags.',
    method: 'GET',
    path: '/api/v1/sagas/run-assessments/reports/{reportId}',
    tags: ['sagas', 'run-assessment'],
    parameters: {
      type: 'object',
      properties: {
        reportId: { type: 'string' },
      },
      required: ['reportId'],
    },
  },
  {
    name: 'bizing.sagas.schemaCoverage.reports.list',
    description:
      'List schema-baseline coverage reports imported from markdown (not from run execution).',
    method: 'GET',
    path: '/api/v1/sagas/schema-coverage/reports',
    tags: ['sagas', 'schema-coverage'],
    parameters: {
      type: 'object',
      properties: {
        limit: { type: 'number', default: 100 },
      },
    },
  },
  {
    name: 'bizing.sagas.schemaCoverage.reports.get',
    description: 'Get one schema-baseline coverage report with normalized UC coverage items and tags.',
    method: 'GET',
    path: '/api/v1/sagas/schema-coverage/reports/{reportId}',
    tags: ['sagas', 'schema-coverage'],
    parameters: {
      type: 'object',
      properties: {
        reportId: { type: 'string' },
      },
      required: ['reportId'],
    },
  },
  {
    name: 'bizing.sagas.coverage.reports.list',
    description:
      'Legacy alias for run-assessment coverage list. Prefer bizing.sagas.runAssessments.reports.list.',
    method: 'GET',
    path: '/api/v1/sagas/coverage/reports',
    tags: ['sagas', 'coverage', 'legacy'],
    parameters: {
      type: 'object',
      properties: {
        sagaRunId: { type: 'string' },
        sagaDefinitionId: { type: 'string' },
        scopeType: { type: 'string' },
        limit: { type: 'number', default: 100 },
      },
    },
  },
  {
    name: 'bizing.sagas.coverage.reports.get',
    description:
      'Legacy alias for coverage detail. Prefer runAssessments/schemaCoverage endpoints.',
    method: 'GET',
    path: '/api/v1/sagas/coverage/reports/{reportId}',
    tags: ['sagas', 'coverage', 'legacy'],
    parameters: {
      type: 'object',
      properties: {
        reportId: { type: 'string' },
      },
      required: ['reportId'],
    },
  },
  {
    name: 'bizing.sagas.schemaCoverage.import',
    description:
      'Import schema coverage markdown into normalized report/items/tags for dashboard filtering.',
    method: 'POST',
    path: '/api/v1/sagas/schema-coverage/import',
    tags: ['sagas', 'schema-coverage', 'admin'],
    parameters: {
      type: 'object',
      properties: {
        coverageFile: { type: 'string' },
        replaceExisting: { type: 'boolean', default: true },
      },
    },
  },
  {
    name: 'bizing.sagas.library.resetReseed',
    description:
      'Dangerous admin operation: wipe loop data (UC/persona/sagas/runs/coverage/tags) and reseed from canonical docs.',
    method: 'POST',
    path: '/api/v1/sagas/library/reset-reseed',
    tags: ['sagas', 'library', 'admin'],
    parameters: {
      type: 'object',
      properties: {
        useCaseFile: { type: 'string' },
        personaFile: { type: 'string' },
        coverageFile: { type: 'string' },
        linkSagaDefinitions: { type: 'boolean', default: true },
        regenerateSpecs: { type: 'boolean', default: true },
        syncDefinitions: { type: 'boolean', default: true },
        importSchemaCoverage: { type: 'boolean', default: true },
        replaceExistingSchemaCoverage: { type: 'boolean', default: true },
      },
    },
  },
  {
    name: 'bizing.sagas.runs.create',
    description: 'Create one saga run from a saga definition key.',
    method: 'POST',
    path: '/api/v1/sagas/runs',
    tags: ['sagas', 'runs'],
    parameters: {
      type: 'object',
      properties: {
        sagaKey: { type: 'string' },
        bizId: { type: 'string' },
        mode: { type: 'string', enum: ['dry_run', 'live'] },
        runnerLabel: { type: 'string' },
        runContext: { type: 'object' },
      },
      required: ['sagaKey'],
    },
  },
  {
    name: 'bizing.sagas.runs.list',
    description: 'List saga runs for the current user context.',
    method: 'GET',
    path: '/api/v1/sagas/runs',
    tags: ['sagas', 'runs'],
    parameters: {
      type: 'object',
      properties: {
        sagaKey: { type: 'string' },
        status: { type: 'string' },
        limit: { type: 'number', default: 50 },
        includeArchived: { type: 'boolean', default: false },
      },
    },
  },
  {
    name: 'bizing.sagas.runs.archive',
    description: 'Soft-archive one saga run so it is hidden from default run lists.',
    method: 'POST',
    path: '/api/v1/sagas/runs/{runId}/archive',
    tags: ['sagas', 'runs', 'archive'],
    parameters: {
      type: 'object',
      properties: {
        runId: { type: 'string' },
      },
      required: ['runId'],
    },
  },
  {
    name: 'bizing.sagas.runs.archiveBulk',
    description: 'Soft-archive multiple saga runs in one request.',
    method: 'POST',
    path: '/api/v1/sagas/runs/archive',
    tags: ['sagas', 'runs', 'archive'],
    parameters: {
      type: 'object',
      properties: {
        runIds: { type: 'array', items: { type: 'string' } },
      },
      required: ['runIds'],
    },
  },
  {
    name: 'bizing.sagas.runs.get',
    description: 'Get full saga run detail including steps and artifacts.',
    method: 'GET',
    path: '/api/v1/sagas/runs/{runId}',
    tags: ['sagas', 'runs'],
    parameters: {
      type: 'object',
      properties: {
        runId: { type: 'string' },
      },
      required: ['runId'],
    },
  },
  {
    name: 'bizing.sagas.runs.execute',
    description:
      'Execute one pending/running saga run server-side using deterministic runner logic.',
    method: 'POST',
    path: '/api/v1/sagas/runs/{runId}/execute',
    tags: ['sagas', 'runs', 'executor'],
    parameters: {
      type: 'object',
      properties: {
        runId: { type: 'string' },
      },
      required: ['runId'],
    },
  },
  {
    name: 'bizing.sagas.runs.coverage',
    description:
      'Get server coverage verdict (full/partial/gap), failing step reasons, and missing evidence for one run.',
    method: 'GET',
    path: '/api/v1/sagas/runs/{runId}/coverage',
    tags: ['sagas', 'runs', 'coverage'],
    parameters: {
      type: 'object',
      properties: {
        runId: { type: 'string' },
      },
      required: ['runId'],
    },
  },
  {
    name: 'bizing.sagas.runs.actors.list',
    description: 'List run actor virtual identities (email/phone) for one saga run.',
    method: 'GET',
    path: '/api/v1/sagas/runs/{runId}/actors',
    tags: ['sagas', 'runs', 'actors'],
    parameters: {
      type: 'object',
      properties: {
        runId: { type: 'string' },
      },
      required: ['runId'],
    },
  },
  {
    name: 'bizing.sagas.runs.messages.list',
    description: 'List simulated actor messages for one run.',
    method: 'GET',
    path: '/api/v1/sagas/runs/{runId}/messages',
    tags: ['sagas', 'runs', 'messages'],
    parameters: {
      type: 'object',
      properties: {
        runId: { type: 'string' },
        actorKey: { type: 'string' },
      },
      required: ['runId'],
    },
  },
  {
    name: 'bizing.sagas.runs.messages.create',
    description: 'Create one simulated actor message (email/sms/push/in-app) for a run.',
    method: 'POST',
    path: '/api/v1/sagas/runs/{runId}/messages',
    tags: ['sagas', 'runs', 'messages'],
    parameters: {
      type: 'object',
      properties: {
        runId: { type: 'string' },
        stepKey: { type: 'string' },
        fromActorKey: { type: 'string' },
        toActorKey: { type: 'string' },
        channel: { type: 'string', enum: ['email', 'sms', 'push', 'in_app'] },
        subject: { type: 'string' },
        bodyText: { type: 'string' },
        status: { type: 'string', enum: ['queued', 'sent', 'delivered', 'read', 'failed', 'cancelled'] },
        metadata: { type: 'object' },
      },
      required: ['runId', 'toActorKey', 'channel', 'bodyText'],
    },
  },
  {
    name: 'bizing.sagas.steps.reportResult',
    description: 'Update one saga run step status/result payload.',
    method: 'POST',
    path: '/api/v1/sagas/runs/{runId}/steps/{stepKey}/result',
    tags: ['sagas', 'steps'],
    parameters: {
      type: 'object',
      properties: {
        runId: { type: 'string' },
        stepKey: { type: 'string' },
        status: { type: 'string' },
        startedAt: { type: 'string' },
        endedAt: { type: 'string' },
        failureCode: { type: 'string' },
        failureMessage: { type: 'string' },
        resultPayload: { type: 'object' },
        assertionSummary: { type: 'object' },
      },
      required: ['runId', 'stepKey', 'status'],
    },
  },
  {
    name: 'bizing.sagas.artifacts.addSnapshot',
    description:
      'Attach one snapshot to saga run. Preferred: snapshot.v1 `view` blocks that represent what user saw.',
    method: 'POST',
    path: '/api/v1/sagas/runs/{runId}/snapshots',
    tags: ['sagas', 'artifacts', 'snapshots'],
    parameters: {
      type: 'object',
      properties: {
        runId: { type: 'string' },
        stepKey: { type: 'string' },
        screenKey: { type: 'string' },
        title: { type: 'string' },
        format: { type: 'string', enum: ['json', 'yaml'] },
        status: { type: 'string' },
        actorKey: { type: 'string' },
        route: { type: 'string' },
        view: {
          type: 'object',
          properties: {
            route: { type: 'string' },
            title: { type: 'string' },
            subtitle: { type: 'string' },
            blocks: {
              type: 'array',
              description:
                'Array of typed low-fi UI blocks. Examples: alert, stats, key_value, table, list, form, calendar.',
              items: { type: 'object' },
            },
          },
        },
        data: { type: 'object' },
        rawData: {
          type: 'object',
          description:
            'Optional deep-inspection payload (request/response/trace) shown in Data tab.',
        },
      },
      required: ['runId'],
    },
  },
  {
    name: 'bizing.sagas.artifacts.addApiTrace',
    description: 'Attach one API trace artifact to a saga run (optionally step-scoped).',
    method: 'POST',
    path: '/api/v1/sagas/runs/{runId}/traces',
    tags: ['sagas', 'artifacts', 'traces'],
    parameters: {
      type: 'object',
      properties: {
        runId: { type: 'string' },
        stepKey: { type: 'string' },
        title: { type: 'string' },
        trace: { type: 'object' },
        metadata: { type: 'object' },
      },
      required: ['runId', 'trace'],
    },
  },
  {
    name: 'bizing.sagas.artifacts.submitReport',
    description: 'Attach final markdown report to saga run.',
    method: 'POST',
    path: '/api/v1/sagas/runs/{runId}/report',
    tags: ['sagas', 'artifacts', 'reports'],
    parameters: {
      type: 'object',
      properties: {
        runId: { type: 'string' },
        markdown: { type: 'string' },
        summary: { type: 'object' },
      },
      required: ['runId', 'markdown'],
    },
  },
  {
    name: 'bizing.sagas.testMode.next',
    description: 'Get next actionable saga step for agent test-mode sessions.',
    method: 'GET',
    path: '/api/v1/sagas/test-mode/next',
    tags: ['sagas', 'test-mode'],
    parameters: {
      type: 'object',
      properties: {
        runId: { type: 'string' },
        sagaKey: { type: 'string' },
        bizId: { type: 'string' },
      },
    },
  },
]

export function findTool(name: string): ApiToolDefinition | undefined {
  return apiTools.find((tool) => tool.name === name)
}

export function searchTools(query: string): ApiToolDefinition[] {
  const q = query.trim().toLowerCase()
  if (!q) return apiTools

  return apiTools
    .map((tool) => {
      const haystack = `${tool.name} ${tool.description} ${tool.path} ${tool.tags.join(' ')}`.toLowerCase()
      const score = haystack.includes(q) ? 1 : 0
      return { tool, score }
    })
    .filter((entry) => entry.score > 0)
    .map((entry) => entry.tool)
}
