import { defineConfig } from "drizzle-kit";

export default defineConfig({
  /**
   * Unified schema source:
   * - `schema/*` includes shared core modules and canonical booking modules
   * - explicit file list prevents accidental inclusion of legacy experiment files
   *
   * v0 policy:
   * - legacy duplicate booking domains are excluded from generation
   * - migrations are generated from the consolidated canonical model
   */
  schema: [
    "./src/schema/bizes.ts",
    "./src/schema/users.ts",
    "./src/schema/auth.ts",
    "./src/schema/authz.ts",
    "./src/schema/locations.ts",
    "./src/schema/group_accounts.ts",
    "./src/schema/memberships.ts",
    "./src/schema/biz_configs.ts",
    "./src/schema/services.ts",
    "./src/schema/products.ts",
    "./src/schema/product_commerce.ts",
    "./src/schema/sellable_variants.ts",
    "./src/schema/sellable_pricing.ts",
    "./src/schema/service_products.ts",
    "./src/schema/assets.ts",
    "./src/schema/venues.ts",
    "./src/schema/resources.ts",
    "./src/schema/stripe.ts",
    "./src/schema/subjects.ts",
    "./src/schema/enums.ts",
    "./src/schema/offers.ts",
    "./src/schema/supply.ts",
    "./src/schema/time_availability.ts",
    "./src/schema/calendar_sync.ts",
    "./src/schema/fulfillment.ts",
    "./src/schema/payments.ts",
    "./src/schema/compensation.ts",
    "./src/schema/demand_pricing.ts",
    "./src/schema/entitlements.ts",
    "./src/schema/channels.ts",
    "./src/schema/intelligence.ts",
    "./src/schema/education.ts",
    "./src/schema/progression.ts",
    "./src/schema/assessments.ts",
    "./src/schema/audit.ts",
    "./src/schema/extensions.ts",
    "./src/schema/access_rights.ts",
    "./src/schema/checkout.ts",
    "./src/schema/commerce_preferences.ts",
    "./src/schema/sales_quotes.ts",
    "./src/schema/session_interactions.ts",
    "./src/schema/interaction_forms.ts",
    "./src/schema/communications.ts",
    "./src/schema/surveys.ts",
    "./src/schema/promotions.ts",
    "./src/schema/work_management.ts",
    "./src/schema/notes.ts",
    "./src/schema/queue.ts",
    "./src/schema/transportation.ts",
    "./src/schema/marketplace.ts",
    "./src/schema/operations_backbone.ts",
    "./src/schema/enterprise.ts",
    "./src/schema/governance.ts",
    "./src/schema/hipaa.ts",
    "./src/schema/workflows.ts",
    "./src/schema/gifts.ts",
    "./src/schema/participant_obligations.ts",
    "./src/schema/ar.ts",
    "./src/schema/receivables.ts",
    "./src/schema/commitments.ts",
    "./src/schema/sla.ts",
    "./src/schema/tax_fx.ts",
    "./src/schema/leave.ts",
    "./src/schema/offline.ts",
    "./src/schema/reporting.ts",
    "./src/schema/social_graph.ts",
    "./src/schema/api_credentials.ts",
    "./src/schema/credential_exchange.ts",
    "./src/schema/ref_keys.ts",
    "./src/schema/access_library.ts",
    "./src/schema/queue_operations.ts",
    "./src/schema/seating.ts",
    "./src/schema/referral_attribution.ts",
    "./src/schema/payer_eligibility.ts",
    "./src/schema/fulfillment_transfers.ts",
    "./src/schema/shipment_schedules.ts",
    "./src/schema/session_interaction_artifacts.ts",
    "./src/schema/gift_delivery.ts",
    "./src/schema/marketing_performance.ts",
    "./src/schema/crm.ts",
    "./src/schema/supply_batches.ts",
    "./src/schema/sagas.ts",
  ],
  out: "./migrations",
  driver: "pg",
  dbCredentials: {
    connectionString:
      process.env.DATABASE_URL ||
      "postgresql://user:password@localhost:5432/bizing",
  } as any,
  verbose: true,
  strict: false,
});
